# Generated by Django 3.0.7 on 2020-06-15 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='review',
            name='unlikes',
            field=models.ManyToManyField(blank=True, related_name='unliked_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genre',
            name='movie',
            field=models.ManyToManyField(blank=True, related_name='genres', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='director',
            name='movie',
            field=models.ManyToManyField(blank=True, related_name='directors', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='country',
            name='movie',
            field=models.ManyToManyField(blank=True, related_name='nations', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='actor',
            name='movie',
            field=models.ManyToManyField(blank=True, related_name='actors', to='movies.Movie'),
        ),
    ]
